---
title: "Bikeshare_git1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
chi <- read.csv('chicago.csv', sep = ',')
ny <- read.csv('new-york-city.csv', sep = ',')
dc <- read.csv('washington.csv', sep = ',')
```

```{r}
summary(chi$Trip.Duration)
summary(ny$Trip.Duration)
summary(dc$Trip.Duration)
```

```{r}
quantile(chi$Trip.Duration, probs = .99)
quantile(ny$Trip.Duration, probs = .99)
quantile(dc$Trip.Duration, probs = .99)
```

```{r}
chi2 <- chi[chi$Trip.Duration < 5100,]
ny2 <- ny[ny$Trip.Duration < 3400,]
dc2 <- dc[dc$Trip.Duration < 8600,]
```

```{r}
library(ggplot2)
```

```{r}
ggplot(aes(y = Trip.Duration), data = chi2) +
  geom_boxplot() +
  geom_hline(yintercept = sd(chi2$Trip.Duration), color = 'blue') +
  coord_cartesian(ylim = c(0,2000)) +
  ggtitle('Chicago Trip Duration Boxplot') +
  labs(x = 'Trip Duration', y = 'IQR + Median')

ggplot(aes(y = Trip.Duration), data = ny2) +
  geom_boxplot() +
  geom_hline(yintercept = sd(ny2$Trip.Duration), color = 'blue') +
  coord_cartesian(ylim = c(0,2000)) +
  ggtitle('New York Trip Duration Boxplot') +
  labs(x = 'Trip Duration', y = 'IQR + Median')

ggplot(aes(y = Trip.Duration), data = dc2) +
  geom_boxplot() +
  geom_hline(yintercept = sd(dc2$Trip.Duration), color = 'blue') +
  coord_cartesian(ylim = c(0,2000)) +
  ggtitle('Washington Trip Duration Boxplot') +
  labs(x = 'Trip Duration', y = 'IQR + Median')
```

```{r}
sd(chi2$Trip.Duration)
sd(ny2$Trip.Duration)
sd(dc2$Trip.Duration)
```

```{r}
sd(chi2$Trip.Duration)/mean(chi2$Trip.Duration)
sd(ny2$Trip.Duration)/mean(ny2$Trip.Duration)
sd(dc2$Trip.Duration)/mean(dc2$Trip.Duration)
```
